const promptDetails = {
    classification: {
        prompt: `Extract key issues in the comment and then Classify the Comment into 1 of the following categories: Amenities, Ancillary Products, Baggage, Baggage Delivery (damage, waiting time), Boarding Process, Cabin Comfort (cabin temperature, uncomfortable seat backs), Cabin Crew Attitude, Catering (special meal order, temperature), Check in procedures (long check-in process), Cleanliness, Crew attitude, Delay, Generic Developmental, Generic Positive, Ground (Flight Cancellation, Delays, Seat Exchange), Ground Services Agent Attitude, GS attitude, GS procedures (no priority Y/J class, queue control, lack of buses), In-Flight Entertainment (IFE), Meal (taste, food/beverage assortment), Nomad Club, On-Board Products, On Time Performance, Product (Travel kits content, My Seat), Service, Ticket Issues, Transit Services, Travel Agents Attitude, Website & Mobile App, Website/App, Brand change, Other, Unclassified. all comments consisting of the words Nomad, Blue, Diamond, Gold, Silver should be classified as Nomad Club. All comments on a Ticket/Price should be classified as Ticket Issues. Comments with KCTV should be classified as In-Flight Entertainment. All website issue should be classified as Website & Mobile App. All Flight Cancellation, Delays, Seat Exchange should be classified as Ground. Single word comment meaning All or great or everything should be classified as Other. Single word comment meaning Service should be classified as Service. Comments mentioning brand change or rebranding should be classified as Brand Change. When there no comment given, Give Category as NA. When the comment does not match any of the above rules or categories, classify it as Unclassified. The comment to be analyzed is - \n-`,
        //prompt: `Extract key issues in the comment and classify the comment into one or more of the following categories: Amenities, Ancillary Products, Baggage Delivery, Boarding Process, Cabin Comfort, Cabin Crew Attitude, Check-in Procedures, Cleanliness, Generic Developmental, Generic Positive, Ground Services Agent Attitude, Ground, In-Flight Entertainment, Meal, Nomad Club, On Time Performance, On-Board Products, Ticket Issues, Travel Agents Attitude, Transit Services, Website & Mobile App, Lost and Found, Baggage. Classification rules: 1. Comments containing the words Nomad, Blue, Diamond, Gold, Silver must be classified as Nomad Club. 2. Comments about a Ticket/Price must be classified as Ticket Issues. 3. Comments containing KCTV must be classified as In-Flight Entertainment. 4. All website-related issues must be classified as Website & Mobile App. 5. Comments about Flight Cancellations, Delays, or Seat Exchanges must be classified as Ground. 6. Single-word comments meaning All, great, or everything must be classified as Other. 7. Single-word comments meaning Service must be classified as Service. 8. If no comment is provided, assign the category as NA. The comment to be analyzed is - \n-`,
        max_tokens: 2000
    },
    sentiment: { prompt: `Provide overall sentiment score between 0 to 5 for the review\n- Classify the following feedback into 1 of the following categories: Generic, In-Flight Experience, Post-Flight Experience, Pre-Flight Experience, Search & Booking Experience \n-`, 
        max_tokens: 1500 }
}


export default promptDetails;
