const promptDetails = {
    classification: {
        prompt: `Extract key issues in the comment and then Classify the Comment into 1 of the following categories: Amenities, Ancillary Products, Baggage Delivery, Boarding Process, Cabin Comfort, Cabin Crew Attitude, Check in procedures, Cleanliness, Generic Developmental, Generic Positive, Ground Services Agent Attitude, Ground,In-Flight Entertainment, Meal, Nomad Club, On Time Performance, On-Board Products,Ticket Issues,Travel Agents Attitude, Transit Services, Website & Mobile App, Lost and Found,Baggage. all comments consisting of the words Nomad, Blue, Diamond, Gold, Silver should be classified as Nomad Club. All comments on a Ticket/Price should  be classified as  Ticket Issues.Comments with KCTV should be classified as In-Flight Entertainment. All website issue should be classified as Website & Mobile App.All Flight Cancellation,Delays,Seat Exchange should be classiied as Ground.Single word comment meaning All or great or everything should be classified as Other.Single word comment meaning Service should be classified as Service. Give the classified category as output example Cleanliness. When there no comment given, Give Category as NA. The comment to be analyzed is - \n-`,
        //prompt: `Extract key issues in the comment and classify the comment into one or more of the following categories: Amenities, Ancillary Products, Baggage Delivery, Boarding Process, Cabin Comfort, Cabin Crew Attitude, Check-in Procedures, Cleanliness, Generic Developmental, Generic Positive, Ground Services Agent Attitude, Ground, In-Flight Entertainment, Meal, Nomad Club, On Time Performance, On-Board Products, Ticket Issues, Travel Agents Attitude, Transit Services, Website & Mobile App, Lost and Found, Baggage. Classification rules: 1. Comments containing the words Nomad, Blue, Diamond, Gold, Silver must be classified as Nomad Club. 2. Comments about a Ticket/Price must be classified as Ticket Issues. 3. Comments containing KCTV must be classified as In-Flight Entertainment. 4. All website-related issues must be classified as Website & Mobile App. 5. Comments about Flight Cancellations, Delays, or Seat Exchanges must be classified as Ground. 6. Single-word comments meaning All, great, or everything must be classified as Other. 7. Single-word comments meaning Service must be classified as Service. 8. If no comment is provided, assign the category as NA. The comment to be analyzed is - \n-`,
        max_tokens: 2000
    },
    sentiment: { prompt: `Provide overall sentiment score between 0 to 5 for the review\n- Classify the following feedback into 1 of the following categories: Generic, In-Flight Experience, Post-Flight Experience, Pre-Flight Experience, Search & Booking Experience \n-`, 
        max_tokens: 1500 }
}


export default promptDetails;
